export const GET_ALL_CATEGORY="GET_ALL_CATEGORY"
export const GET_ERROR="GET_ERROR"
export const CREATE_CATEGORY="CREATE_CATEGORY"
export const CREATE_PRODUCTS="CREATE_PRODUCTS"
export const GET_ALL_PRODUCTS="GET_ALL_PRODUCTS"
export const GET_PRODUCT_DETAILS="GET_PRODUCT_DETAILS"
export const GET_ONE_CATEGORY="GET_ONE_CATEGORY"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const GET_ALL_CATEGORY_SUB="GET_ALL_CATEGORY_SUB"



